---
- id: python-pypi-version-check
  name: python-pypi-version-check
  description: Check if Python package already exists on PYPI.
  entry: hooks/pypi_bumpversion_check-check
  language: python

- id: find-and-replace-strings
  name: find-and-replace-strings
  description: Check if Python package already exists on PYPI.
  entry: hooks/find_and_replace_strings
  language: python


  # python-pypi-version-check-test /Users/hamed/Desktop/tucows-code/find-and-replace-strings/pyproject.toml
