---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: find-and-replace-strings
        name: find-and-replace-strings
        entry: "./hooks/find_and_replace_strings_package/find_and_replace_strings/main.py"
        language: python
        exclude_types:
          - binary
        args: ["--config", "./hooks/find_and_replace_strings_package/tests-pre-commit-hook/.find-and-replace.json"]
        files: "find_and_replace_strings_package/tests-pre-commit-hook/README_TEST_PRE_COMMIT\\.md$"
        # we need $ to terminate the check to avoid .md.template to be picked by hook
