---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  # -----------------------------
  # PYPI bumpversion check
  # -----------------------------
  - repo: local
    hooks:
      - id: install-pypi_bumpversion_check-requirements
        name: Install PYPI bumpversion check requirements
        entry: sh -c 'python3 -m pip install -r ./opencepk_lib_python_common/pypi_bumpversion_check_package/pypi_bumpversion_check/requirements.txt && exit 0'
        language: system
        always_run: true
  - repo: local
    hooks:
      - id: python-pypi-version-check
        name: python-pypi-version-check
        entry: python3 -m opencepk_lib_python_common.pypi_bumpversion_check_package.pypi_bumpversion_check
        language: python
        exclude_types:
          - binary
        args: ['./opencepk_lib_python_common/pypi_bumpversion_check_package/tests-pre-commit-hook/pyproject.test']
        pass_filenames: false  # Do not pass filenames to the hook (this is important to keep)
