---
name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: test-pre-commit-hook
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11

      - name: Run test-pre-commit-hook.sh for check version package
        run: |
          pip3 install .
