---
name: pre-commit

on:
  pull_request:

permissions: read-all

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install-dependencies
        run: pip install -r hooks/pypi_bumpversion_check_package/pypi_bumpversion_check/requirements.txt
      - name: pre-commit-run
        uses: pre-commit/action@v3.0.0
